### ISSUE TITLE
Some accounts not scraping follower counts

### ISSUE THREAD

**Issue by rainachrobak** [royfrancis/iscrape#1]
Hello! I found this library a while back and have been using it to scrape Instagram followers from about 15 accounts. In the last several months, several (4) accounts that I track have started not working properly. 

This one is working and returns a value (as of today) of 3,436 followers:

url <- get_page_user('tuftsmedicalcenter')
fw <- get_count_follower(url)

This one returns the following error after running the get_page_user function. I've checked that I have the account name correct and I do (https://www.instagram.com/cancercenter/?hl=en). 
Warning message: In get_page_user("cancercenter") :
  Username cancercenter did not return a valid web page.

url <- get_page_user('cancercenter')
fw <- get_count_follower(url)

This one returns the following error after running the get_count_follower function. The get_page_user function seems to have worked properly. 
Error in if (stringr::str_detect(count_value, "k")) mlpy <- 1000 : 
  missing value where TRUE/FALSE needed

url <- get_page_user('brighamandwomens')
fw <- get_count_follower(url)

**Comment by royfrancis** [comment]
Updated. Please reinstall and try again.
